### ISSUE TITLE
Doesn't Seem To Work With Material Theme.

### ISSUE THREAD

**Issue by Onwa1kenobi** [EusebiuCandrea/ToolTipPopupWordTV#16]
Minimum SDK is 23 and it throws a cast exception since the anchor view is cast to `SelectableWordTextView` from the library.
`java.lang.ClassCastException: com.google.android.material.textview.MaterialTextView cannot be cast to com.ecandrea.library.tooltipopwordtv.wordTextView.SelectableWordTextView`

**Comment by EusebiuCandrea** [comment]
Thank you! We'll try to solve this issue and release a new version.

**Comment by Onwa1kenobi** [comment]
Awesome. Thank you for the hard work.

**Comment by EusebiuCandrea** [comment]
Fixed
